// Code generated by Slice Machine. DO NOT EDIT.

import Award from './Award';
import Contact from './Contact';
import Contact2 from './Contact2';
import Image from './Image';
import Main from './Main';
import Project from './Project';
import Text from './Text';

export {
	Award,
	Contact,
	Contact2,
	Image,
	Main,
	Project,
	Text,
};

export const components = {
	award: Award,
	contact: Contact,
	contact2: Contact2,
	image: Image,
	a100: Main,
	project: Project,
	contact: Text,
};
